### ISSUE TITLE
Scaldi 2.13 support

### ISSUE THREAD

**Issue by eugeniyk** [scaldi/scaldi#157]
@dave-handy thanks for peeking scaldi

I've noticed scaldi-akka does not supports scala 2.13; I wanted to add 2.13 support, however it's missing deployment to maven

Therefore, how do you look about migration play & akka projects under current (scaldi main project) one? It will be easier to maintain and release.

**Comment by dave-handy** [comment]
I have considered merging the repositories into a single repository, but I'm not sure how to do that without losing the history from those repositories :-(. If I take on the somewhat significant rewrite to use izumi-reflect (prep for scala3) that will probably be such a big rewrite that the history won't be terribly important.

As far as scaldi-akka itself, see my comment at https://github.com/scaldi/scaldi-akka/issues/4#issuecomment-662496176

Are you an active user of scaldi-akka, or you are using scaldi and akka and it seemed useful..? From my perspective it just seems to be adding extra abstraction that isn't necessary. Also it would need to be updated for the typed actor API.

**Comment by eugeniyk** [comment]
Actually, I've just checked that we don't really use anything from scaldi / akka, only scaldi core..
Tbh I don't see the point of having actor factories since it shouldn't be injectable this way

**Comment by dave-handy** [comment]
Ok great! Sounds like we are on the same page; I agree, don't really understand the motivation for using scaldi as an actor factory.
