### ISSUE TITLE
0.4 -> 0.5 : non-string config injection stopped working

### ISSUE THREAD

**Issue by mauhiz** [scaldi/scaldi#43]
Upgrading scaldi-play from 0.4.x to 0.5, code like this : 
`val timeoutMs = inject[Int](identified by "myApi.timeoutMs")`

stopped working (throws a runtime exception, as it cannot find an adequate binding). I cannot pinpoint the exact regression/change, but if this is a discourage practice it should be documented as such.

**Comment by OlegIlyenko** [comment]
Thanks for reporting this. It sounds like  bug, since nothing has changed in this respect, and the code you've shown supposed to work as before. I will look at it today, and will give you some feedback as soon as I can.

**Comment by mauhiz** [comment]
Thanks Oleg ! Please tell me if you need more info.

**Comment by OlegIlyenko** [comment]
I found the bug, it was very silly error if mine :( Sorry for this. I will release scaldi and scaldi-play v0.5.2 with this bugfix today or tomorrow.

**Comment by mauhiz** [comment]
That was quick ^_^

**Comment by OlegIlyenko** [comment]
Travisci just refused cooperate today :) but I finally managed to release scaldi and scaldi-play version 0.5.3. It would be great if you could check it out and look whether it solves the issue in you app.

**Comment by mauhiz** [comment]
Yes, things are fine now. Thanks again for your quick support!
