### ISSUE TITLE
Version discrepancy across modules

### ISSUE THREAD

**Issue by alkersan** [scaldi/scaldi#53]
Hello Oleg,
I'm totally support modularization that you've done in recent updates. But now I see that versions of few modules are ahead of core module and it breaks nice picture a bit on usage side. For example, as a user of whole scaldi library set, I'd like to declare dependency like this:
```
val scaldiVersion := "0.5.6"
libraryDependencies ++= Seq(
  "org.scaldi" %% "scaldi"        % scaldiVersion,
  "org.scaldi" %% "scaldi-play"   % scaldiVersion,
  "org.scaldi" %% "scaldi-jsr330" % scaldiVersion
)
```
but ```scaldi-play``` is at 0.5.8 now and ```scaldi-jsr``` at 0.5.7 .
From user perspective I think it's reasonable to expect version upgrades across all modules simultaneously, like ```play``` and ```akka``` does.

What do you think?

**Comment by OlegIlyenko** [comment]
Hi Dmytro, in general I would agree with you - I try to keep all library versions in sync as much as possible. Sometimes though, I need to do maintenance releases of different modules. It helps a lot, that libraries have independent versions. This allows me to release some bugfixes, for instance, in scaldi-play independently of the main library. 

I also always make sure that the latest version of a leaf library (like scaldi-akka or scaldi-play) always depends on the latest versions of all of it's dependencies. This means, that in your example you don't really need to add `scaldi-jsr330` and `scaldi` dependencies. You only need `scaldi-play` which will add all required transitive dependencies automatically. 

Some people (myself included) try to avoid usage of transitive dependencies and prefer to make an explicit dependencies, especially if transitive dependency used directly in the project. In this case though, I would consider all scaldi libraries very closely related, and would include only `scaldi-akka` or/and `scaldi-play` in play or akka project.
