### ISSUE TITLE
Default constructor parameter injection won't work in Play sbt environment.

### ISSUE THREAD

**Issue by andrey-chernyshev** [scaldi/scaldi#64]
It seems the problem is in this code:

```scala
package scaldi.util
...
object ReflectionHelper {
...
  def getDefaultValueOfParam[T, C](paramName: String)(implicit tt: TypeTag[C]) = {
...
      case Some(constructor) =>
        constructor.paramLists.headOption.toList.flatten.zipWithIndex.find (_._1.name.decodedName.toString == paramName) match {
          case Some((param, idx)) if param.isTerm && param.asTerm.isParamWithDefault =>
            import universe._

            val names = universe.asInstanceOf[StdNames with Names]
            val name = names.nme.defaultGetterName(names.nme.CONSTRUCTOR, idx + 1).encodedName.toString
            val mirror = runtimeMirror(this.getClass.getClassLoader)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
```
When running Play 2.4 projects with a command like `sbt run`,  the code
`this.getClass.getClassLoader` evaluates to a "PlayDependencyClassLoader" which scope is limited to a dependent library classes only  (e.g. scaldi and other jars). This loader won't see the companion class for `C` as desired. The application classes, including the one referenced by  TypeTag[C], are loaded by a child classloader named like "ReloadableClassLoader(v1)". 

What if use `tt.mirror.classLoader` instead of `this.getClass.getClassLoader` - guess this should this fix the issue for Play and other app container environments?

**Comment by OlegIlyenko** [comment]
You are totally correct, it's a wrong classloader used there. Play normally puts app's classloader in a context classloader of active thread. There is even a helper function to get a proper classloader, but it's not used in this case: https://github.com/scaldi/scaldi/blob/master/src/main/scala/scaldi/util/ReflectionHelper.scala#L34

This one should fix it: https://github.com/scaldi/scaldi/commit/b0d0211376a470d7ba22908194af6c3ded922fec

I just published a snapshot with the fix, I would appreciate if you could check it out and see, whether it fixes your issue (just in case):

```scala
resolvers += "Sonatype snapshots" at "https://oss.sonatype.org/content/repositories/snapshots/"
libraryDependencies += "org.sangria-graphql" %% "sangria" % "0.4.3-SNAPSHOT"
```

**Comment by andrey-chernyshev** [comment]
Yes, it does fix the problem. Thanks!!
