### ISSUE TITLE
Can add Injector  parameter depend on AppComponents class?

### ISSUE THREAD

**Issue by rchatsiri** [scaldi/scaldi#67]
I cannot add Injector parameter number two on class ```AppComponents```. Example before change from
```
class AppComponents(context: Context) extends BuiltInComponentsFromContext(context) with EhCacheComponents {
...
}
```
to
```
class AppComponents(context: Context, implicit inj : Injector) extends BuiltInComponentsFromContext(context) with Injectable with EhCacheComponents {
...
}
```
I improve code from link.[1]. Can AppComponents includes with Injector and Injectable with in AppComponents class.?
[1] https://github.com/mariussoutier/play-angular-require-seed/blob/master/app/AppLoader.scala

**Comment by OlegIlyenko** [comment]
I think you are mixing 2 DI styles that play framework provides: the link points to an example of compile-time DI. Scaldi, on the other hand, is a run-time DI library (similar to guice in this respect). It requires different setup and configuration. 

I would recommend to check play's documentation about this: https://www.playframework.com/documentation/2.5.x/ScalaDependencyInjection

You can also look at an example play application that uses scalding for DI: https://github.com/scaldi/scaldi-play-example

**Comment by rchatsiri** [comment]
My problems on BuiltInComponentsFromContext class overrides  router method such as 
```
lazy val controllerNameA = new.Application.ControllerNameA
override def router: Router = new Routes(controllerNameA,...,...)
```
Controller class on play cannot use Injector parameter on class as 
```
ClassName(implicit inj : Injector) extends Controller with Injectable {
...
}
```
I think Play Framework cannot mix 2 DI styles   because compile time DI must specific controller to  Routes class such as ```Routes(controllerNameA,...,...)```

**Comment by OlegIlyenko** [comment]
> I think Play Framework cannot mix 2 DI styles

indeed, I think you need to choose either compile-time Di or the runtime one. 

Please correct me if I'm wrong, but in your case you are mixing both approaches by using `BuiltInComponentsFromContext` with custom `ApplicationLoader` (compile-time DI) and scaldi (runtime DI). 

Also if I remember correctly generated `Routes` uses `javax.inject.*` annotations, so it's usable with both approaches

**Comment by rchatsiri** [comment]
> Also if I remember correctly generated Routes uses javax.inject.* annotations, so it's usable with both approaches

That's point for generated route on Play framework. Can I use ```class ControllerNameA @injecter()(implicit  inj : Injector) extends Controller with Injectable{...}``` instends of  ``` override def router: Router= new Routes(controllerNameA,...,...)```, right?

**Comment by OlegIlyenko** [comment]
Do you mean `@javax.inject.Inject`? you don't need to use it when you use scaldi. Scaldi itself  support JSR 330 annotations so it's able to wire together the whole play application as long as you use `scaldi.play.ScaldiApplicationLoader `. (this means that `Routes` is automatically available as a binding - you don't need to do or declare anything special for it)

I would suggest to start with https://github.com/scaldi/scaldi-play-example instead of using an exaple of a play application that uses compile-time DI, if you plan to use scaldi in you project. Mixing these  approaches at the same application can become pretty confusing :)

**Comment by rchatsiri** [comment]
> Do you mean @javax.inject.Inject? you don't need to use it when you use scaldi. 
Yes I use @inject with scaldi on class parameters such ```class ControllerNameA @injecter()(implicit inj : Injector) extends Controller with Injectable{...}```  . After was read you content, I understand on your mention.
>  (this means that Routes is automatically available as a binding - you don't need to do or declare anything special for it)
My source codes have deleted declare route object. Code see seems smooth to run with Scaldi.
