### ISSUE TITLE
print warnings for ambiguous dependency resolution

### ISSUE THREAD

**Issue by mberndt123** [scaldi/scaldi#69]
Hi,

in our project we ran into a problem several times: when you inject a value and there is more than one binding for values of that type, Scaldi will simply pick one, I think the last one that was bound. However in some cases it might end up picking the wrong one and this case is unpleasant to debug, because you might not even realise that this is happening. It would be nice to get a warning in such a case. This was also discussed here: 

https://groups.google.com/forum/#!topic/scaldi/meayD2iMQ1o

Cheers,
Matthias

**Comment by Mironor** [comment]
I think I found where the issue is, I will supply a pull request shortly.

**Comment by Mironor** [comment]
The problem is with the line Module.scala: 32

  `def getBindingInternal(identifiers: List[Identifier]) = wordBindings find (_ isDefinedFor identifiers)`

I currently replaced it (in the fork) with this:

 ```
 def getBindingInternal(identifiers: List[Identifier]) = {
    val bindings = getBindingsInternal(identifiers)
    if (bindings.size > 1) println("Warning")

    bindings.headOption
  }
```

But I don't know how the warning should handled, it doesn't seem like there is a logging in the project code, and throwing exception seems to be to harsh. 
@OlegIlyenko any thoughts on this?

**Comment by Mironor** [comment]
I added the fix in #70 , it's now up to @OlegIlyenko to accept/not accept it.

**Comment by OlegIlyenko** [comment]
@mberndt123 sorry for the late reply. I see the problem and would like to help with these kind of issues by improving the library. 

Logging a waning or throwing an exception in case of binding overrides is a bit harsh though. Parts of the library rely on this concept, like testing, for instance. In these situations binding overrides are normal. So I would suggest to try find more subtle ways to assist with these situations.

I think it would be very helpful if you could list some of the concrete situations where you have faced this issue or situations where you accidentally have overridden a binding but didn't meant to do it. Simplified examples (like the original one with `Int` overrides) are helpful to understand the mechanics of binding overrides, but they don't necessarily demonstrate where the actual problem, which you are facing, may come from.

**Comment by bilyush** [comment]
Hi there, I created one more idea around this topic - https://github.com/scaldi/scaldi/pull/71 

One of the use cases from our application: there is a class (controller/service) with ```Int``` parameter. That is part of the config, and the developer forgot to put explicit identifier. At the same time the production Module contains more that one binding for ```Int```. Moreover, module for test can have the values, which work for testing.

**Comment by mberndt123** [comment]
Back when I opened this bug, I was working on a project that used Scaldi. But I have long since left that project behind, and frankly these days I consider run-time dependency injection to be a questionable idea at best. So I'll close this as I have no use for a library like Scaldi.
