### ISSUE TITLE
Release for Scala 2.12

### ISSUE THREAD

**Issue by seratch** [scaldi/scaldi#73]
scala-lang 2.12.0 final is already available. Please publish libs for 2.12 when you have time.

http://get-scala.org/2.12

**Comment by OlegIlyenko** [comment]
Thanks for reminding me! Sure thing, I will release a new version soon together with scaldi-play update

**Comment by ncanibano** [comment]
+1

**Comment by seratch** [comment]
The official website is not updated yet but jar files are already available. http://search.maven.org/#artifactdetails%7Corg.scaldi%7Cscaldi_2.12%7C0.5.8%7Cjar

**Comment by ncanibano** [comment]
tx!
