### ISSUE TITLE
Moving forward with Scaldi

### ISSUE THREAD

**Issue by dave-handy** [scaldi/scaldi#81]
Please read [sangria/#445](https://github.com/sangria-graphql/sangria/issues/445) and [sangria/#446](https://github.com/sangria-graphql/sangria/issues/446).

While sangria is currently a much more active project than scaldi, I suspect there are still quite a few of us out there that are intimately familiar with scaldi and use it every day. I chose to adopt scaldi at my company just as we were choosing to invest more heavily in scala and akka-streams, and it has been a cornerstone of our scala toolbox since then. Working with scaldi was a huge part of developing my scala skills, and I can't say enough good things about the project and Oleg's work.

If you have contributed to scaldi in the past or would like to in the future, please chime in! @yanns is working on getting the ownership of the scaldi org transferred to his company, where Oleg worked since 2013.

The top items I'd like to see tackled (and would be happy to help with):
1. Scala 2.13
2. Play 2.7 was released ~6 weeks ago, and [PR#41](https://github.com/scaldi/scaldi-play/pull/41) needs to be merged, tested, and released
3. [scala-steward](https://github.com/fthomas/scala-steward) support
4. Address lingering issues and PRs

I've also developed one extension in particular to scaldi, which is a Module that can be bound within another Module. I've been hoping to contribute that back, but I'll have to get company approval.

**Comment by dhs3000** [comment]
As I am evaluating whether to use Scaldi, I quickly gave the Scala 2.13 support a go and created a [pull request](https://github.com/scaldi/scaldi/pull/82).

**Comment by justjoheinz** [comment]
it would be lovely to get a new release for play 2.7 out in the wild!

**Comment by sniggel** [comment]
Bump

**Comment by yanns** [comment]
https://github.com/sangria-graphql/sangria/issues/446#issuecomment-589083788

It's probable that Github will never give us the rights.
I'd advise you to start a fork.

**Comment by dave-handy** [comment]
Protenus just finished setting up a fork which can be found at https://github.com/protenus/dipendi
Since apache2 reserves trademarks we were advised to change the name, but the packages remain the same, so it should still be a suitable drop-in replacement.
We've merged the 2.13 PRs and a few other bug fixes and added scala steward.
Play support can be found at https://github.com/protenus/dipendi-play

**Comment by yanns** [comment]
Big news, I'm now an owner of https://github.com/scaldi
I'll not take care of it myself.
But there are some people willing to take others, I can grant them and help them at the beginning.

**Comment by dave-handy** [comment]
Wow! What a journey. If you can grant me some sort of access, I can cherry pick the work my company did over in https://github.com/protenus/dipendi. Just have to revert or leave out our change to the README. We have forks of jsr330 and scaldi-play as well. I'll have to talk to my coworker who set up travis and maven central publishing and see if we'll have any issues there.

The only scala project we haven't forked is the scaldi-akka one, which I've never quite understood.

**Comment by yanns** [comment]
@dave-handy if it's ok for you, I'd like to add you as an owner to make sure that we are at least 2 who can manage the project in the future.
https://yanns.github.io/blog/2020/02/11/open-source-and-sole-maintainers/

**Comment by dave-handy** [comment]
Happy to do it!

**Comment by dave-handy** [comment]
@yanns were you able to publish under the same groupId? It looks like someone has parked scaldi.org, so I'm going to have to register a new (similar) domain name unless i want to pay 200$. It will probably be easier to get the documentation site up and running again under a new domain name anyway.

**Comment by yanns** [comment]
> @yanns were you able to publish under the same groupId?

To do that, you have to open an issue on sonatype like I did for sangria: https://issues.sonatype.org/browse/OSSRH-48782

They will ask you to push something on the repo to prove that you have write access.
In my experience, sonatype is very kind and helpful.

> It looks like someone has parked scaldi.org, so I'm going to have to register a new (similar) domain name unless i want to pay >= 200$. It will probably be easier to get the documentation site up and running again under a new domain name anyway.

Yes, that's an issue that we will also probably have on sangria. I have to take care of this before it's too late.

**Comment by dave-handy** [comment]
scaldi, scaldi-jsr330, and scaldi-play 0.6.0 have been published to OSSRH and mirrored to maven central; this release includes a number of bugfixes and 2.13 support in particular.

Remaining todo items for full maintenance, in order of importance:
- update changelog files for the 0.6.0 release
- reserve a hostname for a documentation site
- learn how documentation site is built and restore that
- possibly deprecate scaldi-akka, which I don't understand the value proposition there
- start reviewing open PRs and issues in each project

I don't think any of these issues block anyone from using scaldi successfully, so I'm going to go ahead and close out this issue and open new issues

**Comment by yanns** [comment]
congrats @dave-handy !!!
